- apt_repository:
    repo: ppa:canonical-hwe-team/powertop
  register: apt_ppa_powertop
- apt:
    update_cache: yes
  when: apt_ppa_powertop.changed
- apt:
    pkg:
      - laptop-mode-tools
      - powertop
    state: present

- template:
    src: laptop-mode/{{ ansible_distribution_release }}/laptop-mode.conf
    dest: /etc/laptop-mode/laptop-mode.conf
    mode: 0644
  register: laptop_mode_conf
- lineinfile:
    path: /etc/laptop-mode/conf.d/runtime-pm.conf
    create: yes # create file if it does not already exist
    regexp: ^AUTOSUSPEND_RUNTIME_DEVID_BLACKLIST=
    line: "AUTOSUSPEND_RUNTIME_DEVID_BLACKLIST=\"{{ laptop_mode_autosuspend_blacklist | join(' ') }}\""
  register: laptop_mode_conf_blacklist
    
- service:
    name: laptop-mode
    state: restarted
  when: laptop_mode_conf.changed or laptop_mode_conf_blacklist.changed
