- name: install sudoers config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    validate: '/usr/sbin/visudo -cf %s'
    mode: 0440
    owner: root
    group: root
    backup: yes
  loop:
    - src: sudoers
      dest: /etc/sudoers
    - src: sudoers.d/sudo_group
      dest: /etc/sudoers.d/sudo_group

- name: update apt repositories if necessary
  apt: update_cache=yes cache_valid_time=3600
- name: install laptop-detect and dmidecode
  apt:
    pkg:
      - laptop-detect
      - dmidecode
    state: present

# Laptop specific tasks
- name: run laptop-detect
  shell: laptop-detect
  changed_when: False
  register: laptop_detect
- name: laptop specific things
  include_tasks: laptop.yml
  when: laptop_detect.rc == 0

# Device specific tasks
- name: run dmidecode
  shell: dmidecode --string system-version
  changed_when: False
  register: dmidecode_system_version
- debug: var=dmidecode_system_version.stdout
- name: Lenovo YOGA 900-13ISK specific things
  include_tasks: lenovo-yoga-900-13ISK.yml
  when: dmidecode_system_version.stdout == "Lenovo YOGA 900-13ISK"

- name: apt repoisitories and packages
  include_tasks: apt-repoisitories-and-packages.yml

- name: snap packages
  include_tasks: snap-packages.yml

# Desktop tasks
- name: Unity Desktop specific things
  import_tasks: desktop-unity.yml
  when: desktop_type == 'unity'

- name: disable services
  service: name="{{ item }}" enabled=no state=stopped
  loop: "{{ services_disable }}"
