# ansible 2.7 does not have a snap module
- name: get status of snap packages to install
  shell: snap list "{{ item }}"
  loop: "{{ snap_packages }}"
  register: snap_packages_check
  failed_when: no
  changed_when: snap_packages_check.rc != 0
  check_mode: no

- name: install required snap packages
  shell: snap install "{{ item.item }}"
  loop: "{{ snap_packages_check.results }}"
  when: snap_packages_check is changed and item.rc != 0

- name: get status of snap packages to remove
  shell: snap list "{{ item }}"
  loop: "{{ snap_packages_remove }}"
  register: snap_packages_remove_check
  failed_when: no
  changed_when: snap_packages_remove_check.rc == 0
  check_mode: no

- name: remove required snap packages
  shell: snap remove "{{ item.item }}"
  loop: "{{ snap_packages_remove_check.results }}"
  when: snap_packages_remove_check is changed and item.rc != 0
